{
 "title": "JsonPlaceholder",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "method", "query": "POST,GET,PUT" },
   { "name": "rateInterval", "query": "30s,1m,2m,5m" },
   { "name": "bucketThres", "query": "0.25,0.5,1,2.5,5" },
   { "name": "datasource", "query": "prometheus" },
   { "name": "app", "query": "zhiyoufygo,harix-auto-go" }
  ]
 },
 "panels": [
  { "title": "Zhiyoufygo", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Virtual Users",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(zhiyoufygo_script_jobs_active)",
     "legendFormat": "VUs"
    }
   ]
  },
  {
   "title": "CPU Usage Percent",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum(rate(process_cpu_seconds_total{app=~\"$app\"}[$rateInterval])) by (instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "JsonPlaceholder", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Success Rate",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "sum(rate(jsonplaceholder_api_requests_total{code=~\"2.*\",method=~\"$method\"}[$rateInterval])) / sum(rate(jsonplaceholder_api_requests_total{method=~\"$method\"}[$rateInterval]))",
     "legendFormat": "Success Rate"
    }
   ]
  },
  {
   "title": "Below Duration ${bucketThres}s Percent",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 6 },
   "targets": [
    {
     "expr": "sum(rate(jsonplaceholder_api_request_duration_seconds_bucket{le=\"$bucketThres\",method=~\"$method\"}[$rateInterval])) / sum(rate(jsonplaceholder_api_request_duration_seconds_count{method=~\"$method\"}[$rateInterval]))",
     "legendFormat": "Percent"
    }
   ]
  },
  {
   "title": "Request Volume Total",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "round(sum(rate(jsonplaceholder_api_requests_total{method=~\"$method\"}[$rateInterval])), 0.01)",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Request Duration - 90%",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 11 },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum(rate(jsonplaceholder_api_request_duration_seconds_bucket{method=~\"$method\"}[$rateInterval])) by (le))",
     "legendFormat": "duration"
    }
   ]
  },
  {
   "title": "Request Volume By Method",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "round(sum (\r\n  rate(jsonplaceholder_api_requests_total[$rateInterval])\r\n) by (method), 0.01)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Duration Average",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "sum(rate(jsonplaceholder_api_request_duration_seconds_sum{method=~\"$method\"}[$rateInterval])) / sum(rate(jsonplaceholder_api_request_duration_seconds_count{method=~\"$method\"}[$rateInterval]))",
     "legendFormat": "Duration"
    }
   ]
  }
 ]
}