FROM golang:1.21

RUN apt-get update && apt-get install -y --no-install-recommends \
		iputils-ping \
		dnsutils \
        vim \
        procps \
        fontconfig \
        tcpdump \
        net-tools \
        coreutils

# Add Tini
COPY zhiyoufygo/bin/ /usr/bin/

WORKDIR /app-build-base

COPY stomp stomp
COPY zhiyoufygo zhiyoufygo

WORKDIR /app-build-base/zhiyoufygo

RUN go build

ENTRYPOINT ["/usr/bin/tini", "--"]

CMD ["sleep", "infinity"]
