version: '3.1'
  
services:
  prometheus:
    image: bitnami/prometheus:2.47.0
    container_name: prometheus
    restart: unless-stopped    
    volumes:
      - /srv/prometheus/data:/opt/bitnami/prometheus/data
      - ./prometheus.yml:/opt/bitnami/prometheus/conf/prometheus.yml
    ports:
      - 9090:9090
