package com.example.zhiyoufy.server.elk;

public class ZhiyoufyElkRecordConsts {
	public static class Type {
		public static final String ZHIYOUFY_ELK_SWITCH_GET_STATE = "ZHIYOUFY_ELK_SWITCH_GET_STATE";
		public static final String ZHIYOUFY_ELK_SWITCH_SET_ALL = "ZHIYOUFY_ELK_SWITCH_SET_ALL";
		public static final String ZHIYOUFY_ELK_SWITCH_SET_SOME = "ZHIYOUFY_ELK_SWITCH_SET_SOME";

		public static final String ZHIYOUFY_ELK_AGG_DATEHISTOGRAM = "ZHIYOUFY_ELK_AGG_DATEHISTOGRAM";
		public static final String ZHIYOUFY_ELK_AGG_TERM = "ZHIYOUFY_ELK_AGG_TERM";

		//region UMS
		public static final String ZHIYOUFY_UMS_USER_FORM_LOGIN = "ZHIYOUFY_UMS_USER_FORM_LOGIN";
		public static final String ZHIYOUFY_UMS_USER_GET_USER_INFO = "ZHIYOUFY_UMS_USER_GET_USER_INFO";
		public static final String ZHIYOUFY_UMS_USER_LOGOUT = "ZHIYOUFY_UMS_USER_LOGOUT";
		public static final String ZHIYOUFY_UMS_USER_REGISTER = "ZHIYOUFY_UMS_USER_REGISTER";
		public static final String ZHIYOUFY_UMS_USER_REQUEST_ID_CODE = "ZHIYOUFY_UMS_USER_REQUEST_ID_CODE";

		public static final String ZHIYOUFY_UMS_USER_ADD_USER = "ZHIYOUFY_UMS_USER_ADD_USER";
		public static final String ZHIYOUFY_UMS_USER_DEL_USER = "ZHIYOUFY_UMS_USER_DEL_USER";
		public static final String ZHIYOUFY_UMS_USER_GET_USER_BASE_LIST =
				"ZHIYOUFY_UMS_USER_GET_USER_BASE_LIST";
		public static final String ZHIYOUFY_UMS_USER_GET_USER_LIST =
				"ZHIYOUFY_UMS_USER_GET_USER_LIST";
		public static final String ZHIYOUFY_UMS_USER_GET_USER_ROLE_LIST =
				"ZHIYOUFY_UMS_USER_GET_USER_ROLE_LIST";
		public static final String ZHIYOUFY_UMS_USER_UPDATE_USER = "ZHIYOUFY_UMS_USER_UPDATE_USER";
		public static final String ZHIYOUFY_UMS_USER_UPDATE_USER_PASSWORD =
				"ZHIYOUFY_UMS_USER_UPDATE_USER_PASSWORD";
		public static final String ZHIYOUFY_UMS_USER_UPDATE_USER_ROLE_LIST =
				"ZHIYOUFY_UMS_USER_UPDATE_USER_ROLE_LIST";

		public static final String ZHIYOUFY_UMS_USER_ADD_PERMISSION =
				"ZHIYOUFY_UMS_USER_ADD_PERMISSION";
		public static final String ZHIYOUFY_UMS_USER_DEL_PERMISSION =
				"ZHIYOUFY_UMS_USER_DEL_PERMISSION";
		public static final String ZHIYOUFY_UMS_USER_GET_PERMISSION_LIST =
				"ZHIYOUFY_UMS_USER_GET_PERMISSION_LIST";
		public static final String ZHIYOUFY_UMS_USER_UPDATE_PERMISSION =
				"ZHIYOUFY_UMS_USER_UPDATE_PERMISSION";

		public static final String ZHIYOUFY_UMS_USER_ADD_ROLE =
				"ZHIYOUFY_UMS_USER_ADD_ROLE";
		public static final String ZHIYOUFY_UMS_USER_DEL_ROLE =
				"ZHIYOUFY_UMS_USER_DEL_ROLE";
		public static final String ZHIYOUFY_UMS_USER_GET_ROLE_LIST =
				"ZHIYOUFY_UMS_USER_GET_ROLE_LIST";
		public static final String ZHIYOUFY_UMS_USER_GET_ROLE_PERMISSION_LIST =
				"ZHIYOUFY_UMS_USER_GET_ROLE_PERMISSION_LIST";
		public static final String ZHIYOUFY_UMS_USER_UPDATE_ROLE =
				"ZHIYOUFY_UMS_USER_UPDATE_ROLE";
		public static final String ZHIYOUFY_UMS_USER_UPDATE_ROLE_PERMISSION_LIST =
				"ZHIYOUFY_UMS_USER_UPDATE_ROLE_PERMISSION_LIST";
		public static final String ZHIYOUFY_UMS_USER_VIRTUAL_LOGIN =
				"ZHIYOUFY_UMS_USER_VIRTUAL_LOGIN";
		//endregion

		//region EMS
		public static final String ZHIYOUFY_EMS_ENVIRONMENT_ADD_ENVIRONMENT =
				"ZHIYOUFY_EMS_ENVIRONMENT_ADD_ENVIRONMENT";
		public static final String ZHIYOUFY_EMS_ENVIRONMENT_DEL_ENVIRONMENT =
				"ZHIYOUFY_EMS_ENVIRONMENT_DEL_ENVIRONMENT";
		public static final String ZHIYOUFY_EMS_ENVIRONMENT_GET_ENVIRONMENT_BASE_LIST =
				"ZHIYOUFY_EMS_ENVIRONMENT_GET_ENVIRONMENT_BASE_LIST";
		public static final String ZHIYOUFY_EMS_ENVIRONMENT_GET_ENVIRONMENT_LIST =
				"ZHIYOUFY_EMS_ENVIRONMENT_GET_ENVIRONMENT_LIST";
		public static final String ZHIYOUFY_EMS_ENVIRONMENT_UPDATE_ENVIRONMENT =
				"ZHIYOUFY_EMS_ENVIRONMENT_UPDATE_ENVIRONMENT";

		public static final String ZHIYOUFY_EMS_ENVIRONMENT_ADD_ENVIRONMENT_USER =
				"ZHIYOUFY_EMS_ENVIRONMENT_ADD_ENVIRONMENT_USER";
		public static final String ZHIYOUFY_EMS_ENVIRONMENT_DEL_ENVIRONMENT_USER =
				"ZHIYOUFY_EMS_ENVIRONMENT_DEL_ENVIRONMENT_USER";
		public static final String ZHIYOUFY_EMS_ENVIRONMENT_GET_ENVIRONMENT_USER_LIST =
				"ZHIYOUFY_EMS_ENVIRONMENT_GET_ENVIRONMENT_USER_LIST";
		public static final String ZHIYOUFY_EMS_ENVIRONMENT_UPDATE_ENVIRONMENT_USER =
				"ZHIYOUFY_EMS_ENVIRONMENT_UPDATE_ENVIRONMENT_USER";

		public static final String ZHIYOUFY_EMS_CONFIG_SINGLE_ADD =
				"ZHIYOUFY_EMS_CONFIG_SINGLE_ADD";
		public static final String ZHIYOUFY_EMS_CONFIG_SINGLE_DEL =
				"ZHIYOUFY_EMS_CONFIG_SINGLE_DEL";
		public static final String ZHIYOUFY_EMS_CONFIG_SINGLE_GET_LIST =
				"ZHIYOUFY_EMS_CONFIG_SINGLE_GET_LIST";
		public static final String ZHIYOUFY_EMS_CONFIG_SINGLE_UPDATE =
				"ZHIYOUFY_EMS_CONFIG_SINGLE_UPDATE";

		public static final String ZHIYOUFY_EMS_CONFIG_COLLECTION_ADD =
				"ZHIYOUFY_EMS_CONFIG_COLLECTION_ADD";
		public static final String ZHIYOUFY_EMS_CONFIG_COLLECTION_DEL =
				"ZHIYOUFY_EMS_CONFIG_COLLECTION_DEL";
		public static final String ZHIYOUFY_EMS_CONFIG_COLLECTION_GET_LIST =
				"ZHIYOUFY_EMS_CONFIG_COLLECTION_GET_LIST";
		public static final String ZHIYOUFY_EMS_CONFIG_COLLECTION_UPDATE =
				"ZHIYOUFY_EMS_CONFIG_COLLECTION_UPDATE";

		public static final String ZHIYOUFY_EMS_CONFIG_ITEM_ADD =
				"ZHIYOUFY_EMS_CONFIG_ITEM_ADD";
		public static final String ZHIYOUFY_EMS_CONFIG_ITEM_DEL =
				"ZHIYOUFY_EMS_CONFIG_ITEM_DEL";
		public static final String ZHIYOUFY_EMS_CONFIG_ITEM_GET_LIST =
				"ZHIYOUFY_EMS_CONFIG_ITEM_GET_LIST";
		public static final String ZHIYOUFY_EMS_CONFIG_ITEM_UPDATE =
				"ZHIYOUFY_EMS_CONFIG_ITEM_UPDATE";
		//endregion

		//region PMS
		public static final String ZHIYOUFY_PMS_PROJECT_ADD =
				"ZHIYOUFY_PMS_PROJECT_ADD";
		public static final String ZHIYOUFY_PMS_PROJECT_DEL =
				"ZHIYOUFY_PMS_PROJECT_DEL";
		public static final String ZHIYOUFY_PMS_PROJECT_GET_BASE_LIST =
				"ZHIYOUFY_PMS_PROJECT_GET_BASE_LIST";
		public static final String ZHIYOUFY_PMS_PROJECT_GET_LIST =
				"ZHIYOUFY_PMS_PROJECT_GET_LIST";
		public static final String ZHIYOUFY_PMS_PROJECT_UPDATE =
				"ZHIYOUFY_PMS_PROJECT_UPDATE";

		public static final String ZHIYOUFY_PMS_PROJECT_ADD_USER =
				"ZHIYOUFY_PMS_PROJECT_ADD_USER";
		public static final String ZHIYOUFY_PMS_PROJECT_DEL_USER =
				"ZHIYOUFY_PMS_PROJECT_DEL_USER";
		public static final String ZHIYOUFY_PMS_PROJECT_GET_USER_LIST =
				"ZHIYOUFY_PMS_PROJECT_GET_USER_LIST";
		public static final String ZHIYOUFY_PMS_PROJECT_UPDATE_USER =
				"ZHIYOUFY_PMS_PROJECT_UPDATE_USER";

		public static final String ZHIYOUFY_PMS_JOB_FOLDER_ADD =
				"ZHIYOUFY_PMS_JOB_FOLDER_ADD";
		public static final String ZHIYOUFY_PMS_JOB_FOLDER_DEL =
				"ZHIYOUFY_PMS_JOB_FOLDER_DEL";
		public static final String ZHIYOUFY_PMS_JOB_FOLDER_GET_LIST =
				"ZHIYOUFY_PMS_JOB_FOLDER_GET_LIST";
		public static final String ZHIYOUFY_PMS_JOB_FOLDER_UPDATE =
				"ZHIYOUFY_PMS_JOB_FOLDER_UPDATE";

		public static final String ZHIYOUFY_PMS_JOB_TEMPLATE_ADD =
				"ZHIYOUFY_PMS_JOB_TEMPLATE_ADD";
		public static final String ZHIYOUFY_PMS_JOB_TEMPLATE_DEL =
				"ZHIYOUFY_PMS_JOB_TEMPLATE_DEL";
		public static final String ZHIYOUFY_PMS_JOB_TEMPLATE_GET_LIST =
				"ZHIYOUFY_PMS_JOB_TEMPLATE_GET_LIST";
		public static final String ZHIYOUFY_PMS_JOB_TEMPLATE_UPDATE =
				"ZHIYOUFY_PMS_JOB_TEMPLATE_UPDATE";

		public static final String ZHIYOUFY_PMS_FAVORITE_FOLDER_ADD =
				"ZHIYOUFY_PMS_FAVORITE_FOLDER_ADD";
		public static final String ZHIYOUFY_PMS_FAVORITE_FOLDER_DEL =
				"ZHIYOUFY_PMS_FAVORITE_FOLDER_DEL";
		public static final String ZHIYOUFY_PMS_FAVORITE_FOLDER_GET_LIST =
				"ZHIYOUFY_PMS_FAVORITE_FOLDER_GET_LIST";
		public static final String ZHIYOUFY_PMS_FAVORITE_FOLDER_UPDATE =
				"ZHIYOUFY_PMS_FAVORITE_FOLDER_UPDATE";

		public static final String ZHIYOUFY_PMS_FAVORITE_FOLDER_ADD_TEMPLATE =
				"ZHIYOUFY_PMS_FAVORITE_FOLDER_ADD_TEMPLATE";
		public static final String ZHIYOUFY_PMS_FAVORITE_FOLDER_DEL_TEMPLATE =
				"ZHIYOUFY_PMS_FAVORITE_FOLDER_DEL_TEMPLATE";
		public static final String ZHIYOUFY_PMS_FAVORITE_FOLDER_GET_TEMPLATE_LIST =
				"ZHIYOUFY_PMS_FAVORITE_FOLDER_GET_TEMPLATE_LIST";
		public static final String ZHIYOUFY_PMS_FAVORITE_FOLDER_GET_FOLDER_LIST =
				"ZHIYOUFY_PMS_FAVORITE_FOLDER_GET_FOLDER_LIST";
		//endregion

		//region WMS
		public static final String ZHIYOUFY_WMS_WORKER_APP_ADD =
				"ZHIYOUFY_WMS_WORKER_APP_ADD";
		public static final String ZHIYOUFY_WMS_WORKER_APP_DEL =
				"ZHIYOUFY_WMS_WORKER_APP_DEL";
		public static final String ZHIYOUFY_WMS_WORKER_APP_GET_BASE_LIST =
				"ZHIYOUFY_WMS_WORKER_APP_GET_BASE_LIST";
		public static final String ZHIYOUFY_WMS_WORKER_APP_GET_LIST =
				"ZHIYOUFY_WMS_WORKER_APP_GET_LIST";
		public static final String ZHIYOUFY_WMS_WORKER_APP_UPDATE =
				"ZHIYOUFY_WMS_WORKER_APP_UPDATE";

		public static final String ZHIYOUFY_WMS_WORKER_APP_ADD_USER =
				"ZHIYOUFY_WMS_WORKER_APP_ADD_USER";
		public static final String ZHIYOUFY_WMS_WORKER_APP_DEL_USER =
				"ZHIYOUFY_WMS_WORKER_APP_DEL_USER";
		public static final String ZHIYOUFY_WMS_WORKER_APP_GET_USER_LIST =
				"ZHIYOUFY_WMS_WORKER_APP_GET_USER_LIST";
		public static final String ZHIYOUFY_WMS_WORKER_APP_UPDATE_USER =
				"ZHIYOUFY_WMS_WORKER_APP_UPDATE_USER";

		public static final String ZHIYOUFY_WMS_WORKER_GROUP_ADD =
				"ZHIYOUFY_WMS_WORKER_GROUP_ADD";
		public static final String ZHIYOUFY_WMS_WORKER_GROUP_DEL =
				"ZHIYOUFY_WMS_WORKER_GROUP_DEL";
		public static final String ZHIYOUFY_WMS_WORKER_GROUP_GET_LIST =
				"ZHIYOUFY_WMS_WORKER_GROUP_GET_LIST";
		public static final String ZHIYOUFY_WMS_WORKER_GROUP_UPDATE =
				"ZHIYOUFY_WMS_WORKER_GROUP_UPDATE";

		public static final String ZHIYOUFY_WMS_GROUP_TOKEN_ADD =
				"ZHIYOUFY_WMS_GROUP_TOKEN_ADD";
		public static final String ZHIYOUFY_WMS_GROUP_TOKEN_DEL =
				"ZHIYOUFY_WMS_GROUP_TOKEN_DEL";
		public static final String ZHIYOUFY_WMS_GROUP_TOKEN_GET_LIST =
				"ZHIYOUFY_WMS_GROUP_TOKEN_GET_LIST";
		public static final String ZHIYOUFY_WMS_GROUP_TOKEN_UPDATE =
				"ZHIYOUFY_WMS_GROUP_TOKEN_UPDATE";

		public static final String ZHIYOUFY_WMS_ACTIVE_WORKER_GET_APP_BASE_LIST =
				"ZHIYOUFY_WMS_ACTIVE_WORKER_GET_APP_BASE_LIST";
		public static final String ZHIYOUFY_WMS_ACTIVE_WORKER_GET_GROUP_BASE_LIST =
				"ZHIYOUFY_WMS_ACTIVE_WORKER_GET_GROUP_BASE_LIST";
		public static final String ZHIYOUFY_WMS_ACTIVE_WORKER_GET_WORKER_BASE_LIST =
				"ZHIYOUFY_WMS_ACTIVE_WORKER_GET_WORKER_BASE_LIST";
		public static final String ZHIYOUFY_WMS_ACTIVE_WORKER_DISCONNECT_SESSION =
				"ZHIYOUFY_WMS_ACTIVE_WORKER_DISCONNECT_SESSION";
		//endregion

		//region JMS
		public static final String ZHIYOUFY_JMS_JOB_RUN_START = "ZHIYOUFY_JMS_JOB_RUN_START";
		public static final String ZHIYOUFY_JMS_JOB_RUN_STOP = "ZHIYOUFY_JMS_JOB_RUN_STOP";
		public static final String ZHIYOUFY_JMS_JOB_RUN_UPDATE_PERF_PARALLEL_NUM =
				"ZHIYOUFY_JMS_JOB_RUN_UPDATE_PERF_PARALLEL_NUM";
		public static final String ZHIYOUFY_JMS_JOB_RUN_GET_ACTIVE_BASE_LIST =
				"ZHIYOUFY_JMS_JOB_RUN_GET_ACTIVE_BASE_LIST";
		public static final String ZHIYOUFY_JMS_JOB_RUN_GET_ACTIVE_BASE_SINGLE =
				"ZHIYOUFY_JMS_JOB_RUN_GET_ACTIVE_BASE_SINGLE";

		public static final String ZHIYOUFY_JMS_JOB_RUN_GET_SINGLE_RESULT =
				"ZHIYOUFY_JMS_JOB_RUN_GET_SINGLE_RESULT";

		public static final String ZHIYOUFY_JMS_JOB_RUN_GET_RESULT_LIST =
				"ZHIYOUFY_JMS_JOB_RUN_GET_RESULT_LIST";
		public static final String ZHIYOUFY_JMS_JOB_RUN_GET_CHILD_RESULT_LIST =
				"ZHIYOUFY_JMS_JOB_RUN_GET_CHILD_RESULT_LIST";

		public static final String ZHIYOUFY_JMS_JOB_SCHEDULE_ADD =
				"ZHIYOUFY_JMS_JOB_SCHEDULE_ADD";
		public static final String ZHIYOUFY_JMS_JOB_SCHEDULE_DEL =
				"ZHIYOUFY_JMS_JOB_SCHEDULE_DEL";
		public static final String ZHIYOUFY_JMS_JOB_SCHEDULE_GET_LIST =
				"ZHIYOUFY_JMS_JOB_SCHEDULE_GET_LIST";
		public static final String ZHIYOUFY_JMS_JOB_SCHEDULE_UPDATE =
				"ZHIYOUFY_JMS_JOB_SCHEDULE_UPDATE";
		//endregion
	}

	public static class Tag {
		public static final String ZHIYOUFY_ELK_SWITCH = "ZHIYOUFY_ELK_SWITCH";
		public static final String ZHIYOUFY_ELK_SWITCH_READ = "ZHIYOUFY_ELK_SWITCH_READ";
		public static final String ZHIYOUFY_ELK_SWITCH_WRITE = "ZHIYOUFY_ELK_SWITCH_WRITE";

		public static final String ZHIYOUFY_ELK_AGG = "ZHIYOUFY_ELK_AGG";
		public static final String ZHIYOUFY_ELK_AGG_READ = "ZHIYOUFY_ELK_AGG_READ";

		public static final String ZHIYOUFY_UMS_USER = "ZHIYOUFY_UMS_USER";
		public static final String ZHIYOUFY_UMS_USER_READ = "ZHIYOUFY_UMS_USER_READ";
		public static final String ZHIYOUFY_UMS_USER_WRITE = "ZHIYOUFY_UMS_USER_WRITE";

		//region EMS
		public static final String ZHIYOUFY_EMS_ENVIRONMENT = "ZHIYOUFY_EMS_ENVIRONMENT";
		public static final String ZHIYOUFY_EMS_ENVIRONMENT_READ = "ZHIYOUFY_EMS_ENVIRONMENT_READ";
		public static final String ZHIYOUFY_EMS_ENVIRONMENT_WRITE = "ZHIYOUFY_EMS_ENVIRONMENT_WRITE";

		public static final String ZHIYOUFY_EMS_CONFIG_SINGLE = "ZHIYOUFY_EMS_CONFIG_SINGLE";
		public static final String ZHIYOUFY_EMS_CONFIG_SINGLE_READ = "ZHIYOUFY_EMS_CONFIG_SINGLE_READ";
		public static final String ZHIYOUFY_EMS_CONFIG_SINGLE_WRITE = "ZHIYOUFY_EMS_CONFIG_SINGLE_WRITE";

		public static final String ZHIYOUFY_EMS_CONFIG_COLLECTION = "ZHIYOUFY_EMS_CONFIG_COLLECTION";
		public static final String ZHIYOUFY_EMS_CONFIG_COLLECTION_READ = "ZHIYOUFY_EMS_CONFIG_COLLECTION_READ";
		public static final String ZHIYOUFY_EMS_CONFIG_COLLECTION_WRITE = "ZHIYOUFY_EMS_CONFIG_COLLECTION_WRITE";

		public static final String ZHIYOUFY_EMS_CONFIG_ITEM = "ZHIYOUFY_EMS_CONFIG_ITEM";
		public static final String ZHIYOUFY_EMS_CONFIG_ITEM_READ = "ZHIYOUFY_EMS_CONFIG_ITEM_READ";
		public static final String ZHIYOUFY_EMS_CONFIG_ITEM_WRITE = "ZHIYOUFY_EMS_CONFIG_ITEM_WRITE";
		//endregion

		//region PMS
		public static final String ZHIYOUFY_PMS_PROJECT = "ZHIYOUFY_PMS_PROJECT";
		public static final String ZHIYOUFY_PMS_PROJECT_READ = "ZHIYOUFY_PMS_PROJECT_READ";
		public static final String ZHIYOUFY_PMS_PROJECT_WRITE = "ZHIYOUFY_PMS_PROJECT_WRITE";

		public static final String ZHIYOUFY_PMS_JOB_FOLDER = "ZHIYOUFY_PMS_JOB_FOLDER";
		public static final String ZHIYOUFY_PMS_JOB_FOLDER_READ = "ZHIYOUFY_PMS_JOB_FOLDER_READ";
		public static final String ZHIYOUFY_PMS_JOB_FOLDER_WRITE = "ZHIYOUFY_PMS_JOB_FOLDER_WRITE";

		public static final String ZHIYOUFY_PMS_JOB_TEMPLATE = "ZHIYOUFY_PMS_JOB_TEMPLATE";
		public static final String ZHIYOUFY_PMS_JOB_TEMPLATE_READ = "ZHIYOUFY_PMS_JOB_TEMPLATE_READ";
		public static final String ZHIYOUFY_PMS_JOB_TEMPLATE_WRITE = "ZHIYOUFY_PMS_JOB_TEMPLATE_WRITE";

		public static final String ZHIYOUFY_PMS_FAVORITE_FOLDER = "ZHIYOUFY_PMS_FAVORITE_FOLDER";
		public static final String ZHIYOUFY_PMS_FAVORITE_FOLDER_READ = "ZHIYOUFY_PMS_FAVORITE_FOLDER_READ";
		public static final String ZHIYOUFY_PMS_FAVORITE_FOLDER_WRITE = "ZHIYOUFY_PMS_FAVORITE_FOLDER_WRITE";
		//endregion

		//region WMS
		public static final String ZHIYOUFY_WMS_WORKER_APP = "ZHIYOUFY_WMS_WORKER_APP";
		public static final String ZHIYOUFY_WMS_WORKER_APP_READ = "ZHIYOUFY_WMS_WORKER_APP_READ";
		public static final String ZHIYOUFY_WMS_WORKER_APP_WRITE = "ZHIYOUFY_WMS_WORKER_APP_WRITE";

		public static final String ZHIYOUFY_WMS_WORKER_GROUP = "ZHIYOUFY_WMS_WORKER_GROUP";
		public static final String ZHIYOUFY_WMS_WORKER_GROUP_READ = "ZHIYOUFY_WMS_WORKER_GROUP_READ";
		public static final String ZHIYOUFY_WMS_WORKER_GROUP_WRITE = "ZHIYOUFY_WMS_WORKER_GROUP_WRITE";

		public static final String ZHIYOUFY_WMS_GROUP_TOKEN = "ZHIYOUFY_WMS_GROUP_TOKEN";
		public static final String ZHIYOUFY_WMS_GROUP_TOKEN_READ = "ZHIYOUFY_WMS_GROUP_TOKEN_READ";
		public static final String ZHIYOUFY_WMS_GROUP_TOKEN_WRITE = "ZHIYOUFY_WMS_GROUP_TOKEN_WRITE";

		public static final String ZHIYOUFY_WMS_ACTIVE_WORKER = "ZHIYOUFY_WMS_ACTIVE_WORKER";
		public static final String ZHIYOUFY_WMS_ACTIVE_WORKER_READ = "ZHIYOUFY_WMS_ACTIVE_WORKER_READ";
		public static final String ZHIYOUFY_WMS_ACTIVE_WORKER_WRITE = "ZHIYOUFY_WMS_ACTIVE_WORKER_WRITE";
		//endregion

		//region JMS
		public static final String ZHIYOUFY_JMS_JOB_RUN = "ZHIYOUFY_JMS_JOB_RUN";
		public static final String ZHIYOUFY_JMS_JOB_RUN_READ = "ZHIYOUFY_JMS_JOB_RUN_READ";
		public static final String ZHIYOUFY_JMS_JOB_RUN_WRITE = "ZHIYOUFY_JMS_JOB_RUN_WRITE";
		public static final String ZHIYOUFY_JMS_JOB_SCHEDULE = "ZHIYOUFY_JMS_JOB_SCHEDULE";
		public static final String ZHIYOUFY_JMS_JOB_SCHEDULE_READ = "ZHIYOUFY_JMS_JOB_SCHEDULE_READ";
		public static final String ZHIYOUFY_JMS_JOB_SCHEDULE_WRITE = "ZHIYOUFY_JMS_JOB_SCHEDULE_WRITE";
		//endregion
	}
}
