version: '3.1'
  
services:
  grafana:
    image: grafana/grafana:10.1.4
    container_name: grafana
    restart: unless-stopped
    environment:
      - GF_SERVER_ROOT_URL=${GF_SERVER_ROOT_URL}
    volumes:
      - /srv/grafana/data:/var/lib/grafana
    ports:
      - 3000:3000
